name: Python Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(f'Python {sys.version}')"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip list

    - name: Check imports
      run: |
        python scripts/check_imports.py

    - name: Run unit tests
      run: |
        python scripts/run_tests.py -m "unit"

    - name: Run integration tests
      run: |
        python scripts/run_tests.py -m "integration"

    - name: Test with coverage
      run: |
        python -m pip install pytest-cov
        cd project/task4 && python -m pytest ../../tests/task4/ -v --cov=core --cov=players --cov=strategies --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./project/task4/coverage.xml
        flags: unittests
        name: codecov-umbrella
